### ISSUE TITLE
Surge Playback Not Working

### ISSUE THREAD

**Issue by 0xcaff** [forte-music/web#44]
Playing music doesn't seem to be working on the demo site. It might have something to do with gitlfs.

**Comment by 0xcaff** [comment]
Options:

1. Create a docker container with node and git lfs.

2. Install git-lfs at runtime.

3. Don't use git lfs and instead put the files in a git submodule.

4. Don't use git lfs and instead fetch the files at runtime.

5. Don't use git lfs and instead store files in an npm package.

**Comment by Mcat12** [comment]
6. Dont' use git lfs and instead put the files in the repo?

**Comment by 0xcaff** [comment]
We could do 6 but I believe the performance of the repository suffers significantly. I'll check again. It will get worse because I plan to add at least one more track for some variety.

**Comment by 0xcaff** [comment]
Let's not use git lfs. It is overkill. All those options are overkill. Let's just link to random audio files on the internet.
